# Generated by Django 6.0.3 on 2026-03-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_projectrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
